<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="project"
    nsURI="http:///org/polymap/core/project.ecore" nsPrefix="org.polymap.core.project">
  <eClassifiers xsi:type="ecore:EClass" name="Layer" eSuperTypes="#//ILayer ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="map" eType="#//Map" transient="true"
        eOpposite="#//Map/layers"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Map" eSuperTypes="#//IMap ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="layers" upperBound="-1"
        eType="#//Layer" containment="true" resolveProxies="false" eOpposite="#//Layer/map"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="maps" upperBound="-1" eType="#//Map"
        containment="true" resolveProxies="false" eOpposite="#//Map/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Map"
        transient="true" eOpposite="#//Map/maps"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IProject" instanceClassName="org.polymap.core.project.IProject"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Project" eSuperTypes="#//IProject ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IMap" instanceClassName="org.polymap.core.project.IMap"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ILayer" instanceClassName="org.polymap.core.project.ILayer"
      abstract="true" interface="true"/>
</ecore:EPackage>
